shell:
  program: /bin/bash
  args:
    - -c
    - "tmux"

window:
  startup_mode: Maximized
  decorations: none
  opacity: 0.98

font:
  normal:
    family: Hack Nerd Font
    style: Regular

  size: 10.0
