[font]
size = 10.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[shell]
args = ["--login", "-c", "tmux"]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0.98
startup_mode = "Maximized"

